version: 2.1

executors:
  nodejs:
    docker:
      - image: circleci/node:latest

jobs:
  publish:
    executor: nodejs
    working_directory: ~/tmp
    steps:
      - run:
          name: Setup GIT email
          command: git config --global user.email "developer@keen.io"
      - run:
          name: Setup GIT user
          command: git config --global user.name "Keen Developer"
      - checkout
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
      - run:
          name: Install dependencies
          command: yarn && npx lerna bootstrap
      - run:
          name: Build packages
          command: npx lerna run build
      - add_ssh_keys:
          fingerprints:
            - "79:d9:37:f7:b9:63:5a:f4:35:d4:ad:b2:72:5d:34:a9"
      - run:
          name: Publish
          command: npx lerna publish --conventional-commits --yes
  build:
    executor: nodejs
    working_directory: ~/tmp
    steps:
      - checkout
      - restore_cache:
          key: npm-deps-{{ arch }}-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          command: yarn install
      - save_cache:
          key: npm-deps-{{ arch }}-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run:
          name: Lint
          command: yarn lint
      - run:
          name: Unit Tests
          command: yarn test:ci
      - run:
          name: Build
          command: npx lerna run build

workflows:
  version: 2
  release:
    jobs:
      - publish:
          filters:
            branches:
              only: chore/publish-ci
            tags:
              ignore: /.*/
  ci:
    jobs:
      - build:
          filters:
            branches:
              only: /.*/
            tags:
              ignore: /.*/
